name: Flat
on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - postprocess.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv
          downloaded_filename: owid-covid-data-extract.csv
          postprocess: postprocess.js
